
import { useMemo } from 'react';
import { useFinancialData } from './useFinancialData';

/**
 * Hook for calculating equipment ROI
 * @returns {Object} ROI calculations
 */
export const useEquipmentROI = () => {
  const { data, loading } = useFinancialData();

  const roiData = useMemo(() => {
    const { equipment, bookings, expenses } = data;

    if (!equipment || equipment.length === 0) {
      return [];
    }

    return equipment.map(eq => {
      // Calculate revenue generated by this equipment
      // (This is simplified - in reality you'd track which equipment was used in each booking)
      const equipmentRevenue = bookings
        .filter(b => b.plan?.name?.toLowerCase().includes(eq.name?.toLowerCase()))
        .reduce((sum, b) => sum + (b.total_price || 0), 0);

      // Calculate expenses for this equipment
      const equipmentExpenses = expenses
        .filter(exp => exp.equipment_id === eq.id)
        .reduce((sum, exp) => sum + (exp.amount || 0), 0);

      // Initial investment
      const initialInvestment = eq.purchase_price || 0;

      // Total investment (purchase + maintenance)
      const totalInvestment = initialInvestment + equipmentExpenses;

      // Net profit
      const netProfit = equipmentRevenue - totalInvestment;

      // ROI percentage
      const roi = totalInvestment > 0 
        ? ((netProfit / totalInvestment) * 100).toFixed(2)
        : 0;

      // Payback period (in months)
      const monthlyRevenue = equipmentRevenue / 12; // Simplified
      const paybackPeriod = monthlyRevenue > 0
        ? (totalInvestment / monthlyRevenue).toFixed(1)
        : Infinity;

      return {
        id: eq.id,
        name: eq.name,
        type: eq.equipment_type,
        initialInvestment,
        maintenanceCosts: equipmentExpenses,
        totalInvestment,
        revenue: equipmentRevenue,
        netProfit,
        roi: parseFloat(roi),
        paybackPeriod: paybackPeriod === Infinity ? 'N/A' : `${paybackPeriod} months`,
        currentValue: eq.current_value || 0,
      };
    }).sort((a, b) => b.roi - a.roi);
  }, [data]);

  return {
    roiData,
    loading,
  };
};
