create table public.service_availability (
  id bigint generated by default as identity not null,
  service_id integer not null,
  day_of_week integer not null,
  is_available boolean not null default false,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  slot_interval_minutes integer null default 120,
  window_start_time time without time zone null,
  window_end_time time without time zone null,
  constraint service_availability_pkey1 primary key (id),
  constraint service_day_unique unique (service_id, day_of_week),
  constraint service_availability_service_id_fkey foreign KEY (service_id) references services (id) on delete CASCADE,
  constraint service_availability_day_of_week_check check (
    (
      (day_of_week >= 0)
      and (day_of_week <= 6)
    )
  )
) TABLESPACE pg_default;

create trigger on_service_availability_update BEFORE
update on service_availability for EACH row
execute FUNCTION update_service_availability_updated_at ();