create table public.service_availability (
  id bigint generated by default as identity not null,
  service_id integer not null,
  day_of_week integer not null,
  is_available boolean not null default true,
  delivery_start_time time without time zone null,
  delivery_end_time time without time zone null,
  pickup_start_time time without time zone null,
  pickup_end_time time without time zone null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint service_availability_pkey primary key (id),
  constraint service_availability_service_id_day_of_week_key unique (service_id, day_of_week)
) TABLESPACE pg_default;