create table public.stripe_payment_info (
  id bigint generated by default as identity not null,
  booking_id bigint not null,
  stripe_customer_id text null,
  stripe_payment_intent_id text null,
  stripe_charge_id text null,
  stripe_checkout_session_id text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint stripe_payment_info_pkey primary key (id),
  constraint stripe_payment_info_booking_id_key unique (booking_id),
  constraint stripe_payment_info_booking_id_fkey foreign KEY (booking_id) references bookings (id) on delete CASCADE
) TABLESPACE pg_default;