-- Referral dollar wallet and activation lifecycle.
-- Adds pending/available referral balances, immutable ledger, one-time referred-customer enforcement,
-- and automatic activation when referred booking reaches Completed.

ALTER TABLE public.loyalty_settings
  ADD COLUMN IF NOT EXISTS referral_bonus_dollars numeric(10,2) NOT NULL DEFAULT 25.00,
  ADD COLUMN IF NOT EXISTS referral_bonus_activation_rule text NOT NULL DEFAULT 'completed_booking';

ALTER TABLE public.referrals
  ADD COLUMN IF NOT EXISTS pending_booking_id bigint REFERENCES public.bookings(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS reward_activated_at timestamptz,
  ADD COLUMN IF NOT EXISTS referrer_bonus_dollars_awarded numeric(10,2) NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS public.customer_referral_wallets (
  customer_id bigint PRIMARY KEY REFERENCES public.customers(id) ON DELETE CASCADE,
  pending_balance numeric(10,2) NOT NULL DEFAULT 0 CHECK (pending_balance >= 0),
  available_balance numeric(10,2) NOT NULL DEFAULT 0 CHECK (available_balance >= 0),
  total_earned numeric(10,2) NOT NULL DEFAULT 0 CHECK (total_earned >= 0),
  total_redeemed numeric(10,2) NOT NULL DEFAULT 0 CHECK (total_redeemed >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  last_updated timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.referral_wallet_transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,
  referral_id bigint REFERENCES public.referrals(id) ON DELETE SET NULL,
  booking_id bigint REFERENCES public.bookings(id) ON DELETE SET NULL,
  transaction_type text NOT NULL CHECK (
    transaction_type IN (
      'pending_accrual',
      'activated',
      'redeemed',
      'admin_adjustment_add',
      'admin_adjustment_remove',
      'expired',
      'reversed'
    )
  ),
  amount numeric(10,2) NOT NULL CHECK (amount >= 0),
  pending_balance_after numeric(10,2) NOT NULL DEFAULT 0,
  available_balance_after numeric(10,2) NOT NULL DEFAULT 0,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_referral_wallet_transactions_customer_id
  ON public.referral_wallet_transactions(customer_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_referral_wallet_transactions_referral_id
  ON public.referral_wallet_transactions(referral_id);

CREATE INDEX IF NOT EXISTS idx_referrals_pending_booking_id
  ON public.referrals(pending_booking_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_referrals_one_time_per_referee_customer
  ON public.referrals(referee_customer_id)
  WHERE referee_customer_id IS NOT NULL;

DO $$
DECLARE
  v_constraint record;
BEGIN
  FOR v_constraint IN
    SELECT conname
    FROM pg_constraint
    WHERE conrelid = 'public.referrals'::regclass
      AND contype = 'c'
      AND conname ILIKE 'referrals_status_check%'
  LOOP
    EXECUTE format('ALTER TABLE public.referrals DROP CONSTRAINT %I', v_constraint.conname);
  END LOOP;
END
$$;

ALTER TABLE public.referrals
  ADD CONSTRAINT referrals_status_check
  CHECK (status IN (
    'pending',
    'pending_completion',
    'pending_activation',
    'completed',
    'rewarded',
    'expired',
    'cancelled'
  ));

CREATE OR REPLACE FUNCTION public.adjust_referral_wallet(
  p_customer_id bigint,
  p_amount numeric,
  p_transaction_type text,
  p_booking_id bigint DEFAULT NULL,
  p_referral_id bigint DEFAULT NULL,
  p_notes text DEFAULT NULL
)
RETURNS TABLE(already_processed boolean, pending_balance numeric, available_balance numeric)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_amount numeric(10,2);
  v_wallet public.customer_referral_wallets%ROWTYPE;
BEGIN
  IF p_customer_id IS NULL THEN
    RAISE EXCEPTION 'customer_id is required';
  END IF;

  v_amount := round(abs(COALESCE(p_amount, 0)), 2);
  IF v_amount <= 0 THEN
    RAISE EXCEPTION 'Invalid wallet amount';
  END IF;

  INSERT INTO public.customer_referral_wallets (customer_id)
  VALUES (p_customer_id)
  ON CONFLICT (customer_id) DO NOTHING;

  SELECT *
    INTO v_wallet
    FROM public.customer_referral_wallets
   WHERE customer_id = p_customer_id
   FOR UPDATE;

  IF p_referral_id IS NOT NULL
     AND p_transaction_type IN ('pending_accrual', 'activated')
     AND EXISTS (
       SELECT 1
         FROM public.referral_wallet_transactions t
        WHERE t.referral_id = p_referral_id
          AND t.transaction_type = p_transaction_type
     )
  THEN
    already_processed := true;
    pending_balance := COALESCE(v_wallet.pending_balance, 0);
    available_balance := COALESCE(v_wallet.available_balance, 0);
    RETURN NEXT;
    RETURN;
  END IF;

  IF p_booking_id IS NOT NULL
     AND p_transaction_type = 'redeemed'
     AND EXISTS (
       SELECT 1
         FROM public.referral_wallet_transactions t
        WHERE t.customer_id = p_customer_id
          AND t.booking_id = p_booking_id
          AND t.transaction_type = 'redeemed'
     )
  THEN
    already_processed := true;
    pending_balance := COALESCE(v_wallet.pending_balance, 0);
    available_balance := COALESCE(v_wallet.available_balance, 0);
    RETURN NEXT;
    RETURN;
  END IF;

  IF p_transaction_type = 'pending_accrual' THEN
    UPDATE public.customer_referral_wallets
       SET pending_balance = pending_balance + v_amount,
           total_earned = total_earned + v_amount,
           last_updated = now()
     WHERE customer_id = p_customer_id
     RETURNING * INTO v_wallet;
  ELSIF p_transaction_type = 'activated' THEN
    IF COALESCE(v_wallet.pending_balance, 0) < v_amount THEN
      RAISE EXCEPTION 'Insufficient pending referral balance';
    END IF;
    UPDATE public.customer_referral_wallets
       SET pending_balance = pending_balance - v_amount,
           available_balance = available_balance + v_amount,
           last_updated = now()
     WHERE customer_id = p_customer_id
     RETURNING * INTO v_wallet;
  ELSIF p_transaction_type = 'redeemed' THEN
    IF COALESCE(v_wallet.available_balance, 0) < v_amount THEN
      RAISE EXCEPTION 'Insufficient referral dollars';
    END IF;
    UPDATE public.customer_referral_wallets
       SET available_balance = available_balance - v_amount,
           total_redeemed = total_redeemed + v_amount,
           last_updated = now()
     WHERE customer_id = p_customer_id
     RETURNING * INTO v_wallet;
  ELSIF p_transaction_type = 'admin_adjustment_add' THEN
    UPDATE public.customer_referral_wallets
       SET available_balance = available_balance + v_amount,
           total_earned = total_earned + v_amount,
           last_updated = now()
     WHERE customer_id = p_customer_id
     RETURNING * INTO v_wallet;
  ELSIF p_transaction_type = 'admin_adjustment_remove' THEN
    IF COALESCE(v_wallet.available_balance, 0) < v_amount THEN
      RAISE EXCEPTION 'Insufficient referral dollars';
    END IF;
    UPDATE public.customer_referral_wallets
       SET available_balance = available_balance - v_amount,
           total_redeemed = total_redeemed + v_amount,
           last_updated = now()
     WHERE customer_id = p_customer_id
     RETURNING * INTO v_wallet;
  ELSIF p_transaction_type = 'expired' THEN
    UPDATE public.customer_referral_wallets
       SET available_balance = GREATEST(0, available_balance - v_amount),
           pending_balance = GREATEST(0, pending_balance - GREATEST(0, v_amount - available_balance)),
           total_redeemed = total_redeemed + v_amount,
           last_updated = now()
     WHERE customer_id = p_customer_id
     RETURNING * INTO v_wallet;
  ELSE
    RAISE EXCEPTION 'Unsupported transaction type: %', p_transaction_type;
  END IF;

  INSERT INTO public.referral_wallet_transactions (
    customer_id,
    referral_id,
    booking_id,
    transaction_type,
    amount,
    pending_balance_after,
    available_balance_after,
    notes
  ) VALUES (
    p_customer_id,
    p_referral_id,
    p_booking_id,
    p_transaction_type,
    v_amount,
    COALESCE(v_wallet.pending_balance, 0),
    COALESCE(v_wallet.available_balance, 0),
    p_notes
  );

  already_processed := false;
  pending_balance := COALESCE(v_wallet.pending_balance, 0);
  available_balance := COALESCE(v_wallet.available_balance, 0);
  RETURN NEXT;
END;
$$;

CREATE OR REPLACE FUNCTION public.register_referral_for_booking(
  p_booking_id bigint,
  p_referee_customer_id bigint,
  p_referral_code text,
  p_bonus_dollars numeric DEFAULT NULL
)
RETURNS TABLE(
  referral_id bigint,
  pending_recorded boolean,
  already_rewarded boolean,
  blocked_duplicate boolean,
  referrer_customer_id bigint
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_referral public.referrals%ROWTYPE;
  v_bonus numeric(10,2);
  v_wallet_result record;
BEGIN
  IF p_booking_id IS NULL OR p_referee_customer_id IS NULL THEN
    RETURN;
  END IF;

  IF COALESCE(trim(p_referral_code), '') = '' THEN
    RETURN;
  END IF;

  SELECT *
    INTO v_referral
    FROM public.referrals r
   WHERE lower(r.referral_code) = lower(trim(p_referral_code))
   ORDER BY r.id DESC
   LIMIT 1;

  IF NOT FOUND THEN
    RETURN;
  END IF;

  referral_id := v_referral.id;
  referrer_customer_id := v_referral.referrer_customer_id;

  IF v_referral.referrer_customer_id = p_referee_customer_id THEN
    blocked_duplicate := true;
    pending_recorded := false;
    already_rewarded := false;
    RETURN NEXT;
    RETURN;
  END IF;

  IF EXISTS (
    SELECT 1
      FROM public.referrals r
     WHERE r.referee_customer_id = p_referee_customer_id
       AND r.id <> v_referral.id
       AND r.status IN ('pending_completion', 'pending_activation', 'completed', 'rewarded')
  ) THEN
    blocked_duplicate := true;
    pending_recorded := false;
    already_rewarded := false;
    RETURN NEXT;
    RETURN;
  END IF;

  v_bonus := round(COALESCE(p_bonus_dollars, (
    SELECT ls.referral_bonus_dollars
      FROM public.loyalty_settings ls
     ORDER BY ls.id DESC
     LIMIT 1
  ), 25), 2);

  UPDATE public.referrals
     SET referee_customer_id = COALESCE(referee_customer_id, p_referee_customer_id),
         pending_booking_id = COALESCE(pending_booking_id, p_booking_id),
         status = CASE
           WHEN status = 'rewarded' THEN status
           ELSE 'pending_completion'
         END
   WHERE id = v_referral.id
   RETURNING * INTO v_referral;

  already_rewarded := v_referral.status = 'rewarded';
  blocked_duplicate := false;
  pending_recorded := false;

  IF NOT already_rewarded AND v_bonus > 0 THEN
    SELECT *
      INTO v_wallet_result
      FROM public.adjust_referral_wallet(
        v_referral.referrer_customer_id,
        v_bonus,
        'pending_accrual',
        p_booking_id,
        v_referral.id,
        'Referral pending until booking #' || p_booking_id::text || ' reaches Completed'
      ) AS t(already_processed boolean, pending_balance numeric, available_balance numeric);

    pending_recorded := NOT COALESCE(v_wallet_result.already_processed, false);

    UPDATE public.referrals
       SET referrer_bonus_dollars_awarded = GREATEST(COALESCE(referrer_bonus_dollars_awarded, 0), v_bonus)
     WHERE id = v_referral.id;
  END IF;

  RETURN NEXT;
END;
$$;

CREATE OR REPLACE FUNCTION public.activate_referral_for_completed_booking(
  p_booking_id bigint
)
RETURNS TABLE(
  referral_id bigint,
  activated boolean,
  bonus_dollars numeric,
  referrer_customer_id bigint
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_booking record;
  v_referral public.referrals%ROWTYPE;
  v_bonus numeric(10,2);
  v_wallet_result record;
BEGIN
  IF p_booking_id IS NULL THEN
    RETURN;
  END IF;

  SELECT b.id, b.customer_id, b.status
    INTO v_booking
    FROM public.bookings b
   WHERE b.id = p_booking_id
   LIMIT 1;

  IF NOT FOUND OR v_booking.customer_id IS NULL THEN
    RETURN;
  END IF;

  IF lower(COALESCE(v_booking.status, '')) <> 'completed' THEN
    RETURN;
  END IF;

  SELECT *
    INTO v_referral
    FROM public.referrals r
   WHERE r.pending_booking_id = p_booking_id
     AND r.referee_customer_id = v_booking.customer_id
   ORDER BY r.id DESC
   LIMIT 1;

  IF NOT FOUND THEN
    RETURN;
  END IF;

  referral_id := v_referral.id;
  referrer_customer_id := v_referral.referrer_customer_id;

  v_bonus := round(COALESCE(v_referral.referrer_bonus_dollars_awarded, 0), 2);
  IF v_bonus <= 0 THEN
    v_bonus := round(COALESCE((
      SELECT ls.referral_bonus_dollars
        FROM public.loyalty_settings ls
       ORDER BY ls.id DESC
       LIMIT 1
    ), 25), 2);
  END IF;

  bonus_dollars := v_bonus;

  IF v_referral.status = 'rewarded' AND v_referral.reward_activated_at IS NOT NULL THEN
    activated := false;
    RETURN NEXT;
    RETURN;
  END IF;

  UPDATE public.referrals
     SET status = CASE WHEN v_bonus > 0 THEN 'rewarded' ELSE 'completed' END,
         completed_booking_id = COALESCE(completed_booking_id, p_booking_id),
         pending_booking_id = COALESCE(pending_booking_id, p_booking_id),
         completed_at = COALESCE(completed_at, now())
   WHERE id = v_referral.id;

  IF v_bonus > 0 THEN
    SELECT *
      INTO v_wallet_result
      FROM public.adjust_referral_wallet(
        v_referral.referrer_customer_id,
        v_bonus,
        'activated',
        p_booking_id,
        v_referral.id,
        'Referral activated after booking #' || p_booking_id::text || ' completed'
      ) AS t(already_processed boolean, pending_balance numeric, available_balance numeric);

    activated := NOT COALESCE(v_wallet_result.already_processed, false);

    IF activated THEN
      UPDATE public.referrals
         SET reward_activated_at = now(),
             referrer_bonus_dollars_awarded = v_bonus
       WHERE id = v_referral.id;
    END IF;
  ELSE
    activated := false;
  END IF;

  RETURN NEXT;
END;
$$;

CREATE OR REPLACE FUNCTION public.handle_booking_completed_referral_activation()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF lower(COALESCE(NEW.status, '')) = 'completed'
     AND lower(COALESCE(OLD.status, '')) <> 'completed'
  THEN
    PERFORM public.activate_referral_for_completed_booking(NEW.id);
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_activate_referral_on_booking_completed ON public.bookings;
CREATE TRIGGER trg_activate_referral_on_booking_completed
AFTER UPDATE OF status ON public.bookings
FOR EACH ROW
EXECUTE FUNCTION public.handle_booking_completed_referral_activation();

ALTER TABLE public.customer_referral_wallets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.referral_wallet_transactions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admin full access customer_referral_wallets" ON public.customer_referral_wallets;
CREATE POLICY "Admin full access customer_referral_wallets"
  ON public.customer_referral_wallets FOR ALL
  USING (public.is_admin() OR auth.role() = 'service_role')
  WITH CHECK (public.is_admin() OR auth.role() = 'service_role');

DROP POLICY IF EXISTS "Customers read own customer_referral_wallets" ON public.customer_referral_wallets;
CREATE POLICY "Customers read own customer_referral_wallets"
  ON public.customer_referral_wallets FOR SELECT
  USING (customer_id = public.current_customer_id());

DROP POLICY IF EXISTS "Admin full access referral_wallet_transactions" ON public.referral_wallet_transactions;
CREATE POLICY "Admin full access referral_wallet_transactions"
  ON public.referral_wallet_transactions FOR ALL
  USING (public.is_admin() OR auth.role() = 'service_role')
  WITH CHECK (public.is_admin() OR auth.role() = 'service_role');

DROP POLICY IF EXISTS "Customers read own referral_wallet_transactions" ON public.referral_wallet_transactions;
CREATE POLICY "Customers read own referral_wallet_transactions"
  ON public.referral_wallet_transactions FOR SELECT
  USING (customer_id = public.current_customer_id());

GRANT SELECT ON public.customer_referral_wallets TO authenticated;
GRANT SELECT ON public.referral_wallet_transactions TO authenticated;
GRANT ALL ON public.customer_referral_wallets TO service_role;
GRANT ALL ON public.referral_wallet_transactions TO service_role;

GRANT EXECUTE ON FUNCTION public.adjust_referral_wallet(bigint, numeric, text, bigint, bigint, text)
  TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.register_referral_for_booking(bigint, bigint, text, numeric)
  TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.activate_referral_for_completed_booking(bigint)
  TO anon, authenticated, service_role;
