-- Re-create loyalty/referral tables if a mistaken db pull migration dropped them on production.
-- Safe to run repeatedly (IF NOT EXISTS). New local resets use fixed 20260520181837 (no drops).

CREATE TABLE IF NOT EXISTS public.loyalty_settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  points_per_dollar numeric NOT NULL DEFAULT 10,
  points_to_dollar numeric NOT NULL DEFAULT 100,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.loyalty_settings (points_per_dollar, points_to_dollar)
SELECT 10, 100
WHERE NOT EXISTS (SELECT 1 FROM public.loyalty_settings LIMIT 1);

CREATE TABLE IF NOT EXISTS public.loyalty_points (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,
  points_balance integer NOT NULL DEFAULT 0 CHECK (points_balance >= 0),
  total_points_earned integer NOT NULL DEFAULT 0,
  total_points_redeemed integer NOT NULL DEFAULT 0,
  last_updated timestamptz NOT NULL DEFAULT now(),
  UNIQUE (customer_id)
);

CREATE TABLE IF NOT EXISTS public.loyalty_transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,
  transaction_type text NOT NULL CHECK (
    transaction_type IN ('earned', 'redeemed', 'admin_adjustment_add', 'admin_adjustment_remove', 'referral_bonus')
  ),
  points_amount integer NOT NULL,
  booking_id bigint REFERENCES public.bookings(id) ON DELETE SET NULL,
  referral_id bigint,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS loyalty_transactions_earned_booking_unique
  ON public.loyalty_transactions (booking_id)
  WHERE transaction_type = 'earned' AND booking_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.referrals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  referrer_customer_id bigint NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,
  referral_code text NOT NULL UNIQUE,
  referee_email text,
  referee_customer_id bigint REFERENCES public.customers(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'rewarded', 'expired')),
  referrer_points_awarded integer NOT NULL DEFAULT 0,
  referee_coupon_code text,
  completed_booking_id bigint REFERENCES public.bookings(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz
);

CREATE INDEX IF NOT EXISTS referrals_referrer_customer_id_idx ON public.referrals (referrer_customer_id);
CREATE INDEX IF NOT EXISTS referrals_referral_code_idx ON public.referrals (referral_code);

ALTER TABLE public.loyalty_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.loyalty_points ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.loyalty_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.referrals ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admin full access loyalty_settings" ON public.loyalty_settings;
CREATE POLICY "Admin full access loyalty_settings"
  ON public.loyalty_settings FOR ALL
  USING (public.is_admin() OR auth.role() = 'service_role')
  WITH CHECK (public.is_admin() OR auth.role() = 'service_role');

DROP POLICY IF EXISTS "Anyone can read loyalty_settings" ON public.loyalty_settings;
CREATE POLICY "Anyone can read loyalty_settings"
  ON public.loyalty_settings FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Admin full access loyalty_points" ON public.loyalty_points;
CREATE POLICY "Admin full access loyalty_points"
  ON public.loyalty_points FOR ALL
  USING (public.is_admin() OR auth.role() = 'service_role')
  WITH CHECK (public.is_admin() OR auth.role() = 'service_role');

DROP POLICY IF EXISTS "Customers read own loyalty_points" ON public.loyalty_points;
CREATE POLICY "Customers read own loyalty_points"
  ON public.loyalty_points FOR SELECT
  USING (customer_id = public.current_customer_id());

DROP POLICY IF EXISTS "Admin full access loyalty_transactions" ON public.loyalty_transactions;
CREATE POLICY "Admin full access loyalty_transactions"
  ON public.loyalty_transactions FOR ALL
  USING (public.is_admin() OR auth.role() = 'service_role')
  WITH CHECK (public.is_admin() OR auth.role() = 'service_role');

DROP POLICY IF EXISTS "Customers read own loyalty_transactions" ON public.loyalty_transactions;
CREATE POLICY "Customers read own loyalty_transactions"
  ON public.loyalty_transactions FOR SELECT
  USING (customer_id = public.current_customer_id());

DROP POLICY IF EXISTS "Admin full access referrals" ON public.referrals;
CREATE POLICY "Admin full access referrals"
  ON public.referrals FOR ALL
  USING (public.is_admin() OR auth.role() = 'service_role')
  WITH CHECK (public.is_admin() OR auth.role() = 'service_role');

DROP POLICY IF EXISTS "Customers read own referrals" ON public.referrals;
CREATE POLICY "Customers read own referrals"
  ON public.referrals FOR SELECT
  USING (referrer_customer_id = public.current_customer_id());

DROP POLICY IF EXISTS "Customers insert own referrals" ON public.referrals;
CREATE POLICY "Customers insert own referrals"
  ON public.referrals FOR INSERT
  WITH CHECK (referrer_customer_id = public.current_customer_id());

GRANT SELECT ON public.loyalty_settings TO anon, authenticated;
GRANT ALL ON public.loyalty_settings TO service_role;
GRANT SELECT ON public.loyalty_points TO authenticated;
GRANT ALL ON public.loyalty_points TO service_role;
GRANT SELECT ON public.loyalty_transactions TO authenticated;
GRANT ALL ON public.loyalty_transactions TO service_role;
GRANT SELECT, INSERT ON public.referrals TO authenticated;
GRANT ALL ON public.referrals TO service_role;
