-- Durable CRM leads for incomplete checkouts + extend cleanup to upsert them.
-- Reminder cron posts to send-abandoned-checkout-reminder edge function.

CREATE TABLE IF NOT EXISTS public.abandoned_checkouts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL,
  phone text,
  full_name text,
  source text NOT NULL DEFAULT 'pending_payment',
  booking_id bigint REFERENCES public.bookings(id) ON DELETE SET NULL,
  service_name text,
  plan jsonb,
  addons jsonb,
  cart_snapshot jsonb,
  total_price numeric(12,2),
  drop_off_date date,
  pickup_date date,
  status text NOT NULL DEFAULT 'open'
    CHECK (status IN ('open', 'reminded', 'expired', 'converted', 'unsubscribed')),
  reminder_sent_at timestamptz,
  expired_at timestamptz,
  marketing_eligible boolean NOT NULL DEFAULT true,
  tags text[] NOT NULL DEFAULT '{}',
  notes text,
  meta jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS abandoned_checkouts_booking_id_uidx
  ON public.abandoned_checkouts (booking_id);

CREATE INDEX IF NOT EXISTS abandoned_checkouts_email_lower_idx
  ON public.abandoned_checkouts (lower(email));

CREATE INDEX IF NOT EXISTS abandoned_checkouts_status_idx
  ON public.abandoned_checkouts (status);

CREATE INDEX IF NOT EXISTS abandoned_checkouts_created_at_idx
  ON public.abandoned_checkouts (created_at DESC);

COMMENT ON TABLE public.abandoned_checkouts IS
  'CRM leads for customers who reached payment but did not finalize. Expandable for campaigns/coupons.';

CREATE OR REPLACE FUNCTION public.set_abandoned_checkouts_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_abandoned_checkouts_updated_at ON public.abandoned_checkouts;
CREATE TRIGGER trg_abandoned_checkouts_updated_at
  BEFORE UPDATE ON public.abandoned_checkouts
  FOR EACH ROW
  EXECUTE FUNCTION public.set_abandoned_checkouts_updated_at();

ALTER TABLE public.abandoned_checkouts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admin select abandoned_checkouts" ON public.abandoned_checkouts;
CREATE POLICY "Admin select abandoned_checkouts"
  ON public.abandoned_checkouts FOR SELECT
  TO authenticated
  USING (public.is_admin());

DROP POLICY IF EXISTS "Admin update abandoned_checkouts" ON public.abandoned_checkouts;
CREATE POLICY "Admin update abandoned_checkouts"
  ON public.abandoned_checkouts FOR UPDATE
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Admin insert abandoned_checkouts" ON public.abandoned_checkouts;
CREATE POLICY "Admin insert abandoned_checkouts"
  ON public.abandoned_checkouts FOR INSERT
  TO authenticated
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Service role full abandoned_checkouts" ON public.abandoned_checkouts;
CREATE POLICY "Service role full abandoned_checkouts"
  ON public.abandoned_checkouts FOR ALL
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

GRANT SELECT, INSERT, UPDATE ON public.abandoned_checkouts TO authenticated;
GRANT ALL ON public.abandoned_checkouts TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.abandoned_checkouts_id_seq TO authenticated, service_role;

-- Upsert a lead snapshot from a booking row (used by cleanup + reminder).
CREATE OR REPLACE FUNCTION public.upsert_abandoned_checkout_from_booking(
  p_booking_id bigint,
  p_status text DEFAULT 'expired',
  p_set_reminder_sent boolean DEFAULT false
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  b record;
  v_service_name text;
  v_id bigint;
  v_cart jsonb;
BEGIN
  IF p_booking_id IS NULL THEN
    RETURN NULL;
  END IF;

  SELECT *
    INTO b
    FROM public.bookings
   WHERE id = p_booking_id
   LIMIT 1;

  IF NOT FOUND THEN
    RETURN NULL;
  END IF;

  IF COALESCE(b.email, '') = '' THEN
    RETURN NULL;
  END IF;

  v_service_name := COALESCE(
    NULLIF(b.plan->>'name', ''),
    NULLIF(b.plan->'name'->>'name', ''),
    'Service'
  );

  v_cart := jsonb_build_object(
    'booking_id', b.id,
    'plan', b.plan,
    'addons', b.addons,
    'contact_address', b.contact_address,
    'delivery_address', b.delivery_address,
    'drop_off_date', b.drop_off_date,
    'pickup_date', b.pickup_date,
    'drop_off_time_slot', b.drop_off_time_slot,
    'pickup_time_slot', b.pickup_time_slot,
    'total_price', b.total_price,
    'subtotal_before_tax', b.subtotal_before_tax,
    'tax_amount', b.tax_amount,
    'distance_miles', b.distance_miles
  );

  INSERT INTO public.abandoned_checkouts AS ac (
    email,
    phone,
    full_name,
    source,
    booking_id,
    service_name,
    plan,
    addons,
    cart_snapshot,
    total_price,
    drop_off_date,
    pickup_date,
    status,
    reminder_sent_at,
    expired_at,
    marketing_eligible,
    meta
  )
  VALUES (
    lower(trim(b.email)),
    NULLIF(b.phone, ''),
    NULLIF(trim(COALESCE(b.name, concat_ws(' ', b.first_name, b.last_name))), ''),
    'pending_payment',
    b.id,
    v_service_name,
    b.plan,
    b.addons,
    v_cart,
    b.total_price,
    b.drop_off_date::date,
    b.pickup_date::date,
    p_status,
    CASE WHEN p_set_reminder_sent THEN now() ELSE NULL END,
    CASE WHEN p_status = 'expired' THEN now() ELSE NULL END,
    true,
    jsonb_build_object('last_source_status', b.status)
  )
  ON CONFLICT (booking_id)
  DO UPDATE SET
    email = EXCLUDED.email,
    phone = COALESCE(EXCLUDED.phone, ac.phone),
    full_name = COALESCE(EXCLUDED.full_name, ac.full_name),
    service_name = COALESCE(EXCLUDED.service_name, ac.service_name),
    plan = COALESCE(EXCLUDED.plan, ac.plan),
    addons = COALESCE(EXCLUDED.addons, ac.addons),
    cart_snapshot = COALESCE(EXCLUDED.cart_snapshot, ac.cart_snapshot),
    total_price = COALESCE(EXCLUDED.total_price, ac.total_price),
    drop_off_date = COALESCE(EXCLUDED.drop_off_date, ac.drop_off_date),
    pickup_date = COALESCE(EXCLUDED.pickup_date, ac.pickup_date),
    status = CASE
      WHEN ac.status = 'unsubscribed' THEN ac.status
      WHEN ac.status = 'converted' THEN ac.status
      ELSE EXCLUDED.status
    END,
    reminder_sent_at = CASE
      WHEN p_set_reminder_sent THEN COALESCE(ac.reminder_sent_at, now())
      ELSE ac.reminder_sent_at
    END,
    expired_at = CASE
      WHEN p_status = 'expired' THEN COALESCE(ac.expired_at, now())
      ELSE ac.expired_at
    END,
    meta = COALESCE(ac.meta, '{}'::jsonb) || EXCLUDED.meta,
    updated_at = now()
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;

ALTER FUNCTION public.upsert_abandoned_checkout_from_booking(bigint, text, boolean) OWNER TO postgres;
REVOKE ALL ON FUNCTION public.upsert_abandoned_checkout_from_booking(bigint, text, boolean) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.upsert_abandoned_checkout_from_booking(bigint, text, boolean)
  TO service_role, authenticated;

-- Extend cleanup: upsert lead then cancel + restock
CREATE OR REPLACE FUNCTION public.cleanup_abandoned_pending_payment_bookings(
  p_older_than interval DEFAULT interval '2 hours'
)
RETURNS TABLE(
  booking_id bigint,
  restocked boolean,
  cancelled boolean
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  rec record;
  eq jsonb;
  items jsonb := '[]'::jsonb;
  eq_id bigint;
  qty int;
  should_restock boolean;
  did_restock boolean;
BEGIN
  FOR rec IN
    SELECT b.id, b.status, b.addons, b.created_at, b.total_price
    FROM public.bookings b
    WHERE b.status = 'pending_payment'
      AND b.created_at < now() - p_older_than
    ORDER BY b.id
  LOOP
    items := '[]'::jsonb;
    should_restock := false;
    did_restock := false;

    -- Persist CRM lead before cancel (works even if reminder never sent)
    PERFORM public.upsert_abandoned_checkout_from_booking(rec.id, 'expired', false);

    IF rec.addons IS NOT NULL
       AND jsonb_typeof(rec.addons->'equipment') = 'array'
       AND jsonb_array_length(rec.addons->'equipment') > 0
    THEN
      IF COALESCE(rec.addons->>'equipment_hold_active', '') IS DISTINCT FROM 'false' THEN
        should_restock := true;
      END IF;

      IF should_restock THEN
        FOR eq IN SELECT * FROM jsonb_array_elements(rec.addons->'equipment')
        LOOP
          eq_id := NULLIF(COALESCE(eq->>'dbId', eq->>'equipment_id', eq->>'id'), '')::bigint;
          qty := COALESCE(NULLIF(eq->>'quantity', '')::int, 1);
          IF eq_id IS NOT NULL AND qty > 0 THEN
            items := items || jsonb_build_array(
              jsonb_build_object('equipment_id', eq_id, 'quantity', qty)
            );
          END IF;
        END LOOP;

        IF jsonb_array_length(items) > 0 THEN
          PERFORM public.increment_equipment_quantities(items);
          did_restock := true;
        END IF;
      END IF;
    END IF;

    UPDATE public.bookings
    SET
      status = 'Cancelled',
      addons = COALESCE(addons, '{}'::jsonb) || jsonb_build_object('equipment_hold_active', false),
      archive_details = jsonb_build_object(
        'action', 'cancelled',
        'action_at', now(),
        'initiated_by', 'system',
        'notes', 'abandoned_checkout_timeout',
        'original_created_at', rec.created_at,
        'original_total_price', rec.total_price
      )
    WHERE id = rec.id
      AND status = 'pending_payment';

    booking_id := rec.id;
    restocked := did_restock;
    cancelled := FOUND;
    RETURN NEXT;
  END LOOP;
END;
$$;

-- Cron: reminder edge function every 15 minutes
CREATE EXTENSION IF NOT EXISTS pg_cron WITH SCHEMA pg_catalog;
CREATE EXTENSION IF NOT EXISTS pg_net WITH SCHEMA extensions;

DO $cron_setup$
DECLARE
  job RECORD;
BEGIN
  FOR job IN
    SELECT jobid, jobname
    FROM cron.job
    WHERE jobname = 'send-abandoned-checkout-reminder'
  LOOP
    PERFORM cron.unschedule(job.jobid);
  END LOOP;
END;
$cron_setup$;

SELECT cron.schedule(
  'send-abandoned-checkout-reminder',
  '*/15 * * * *',
  $$
  SELECT net.http_post(
    url := (
      SELECT decrypted_secret
      FROM vault.decrypted_secrets
      WHERE name = 'supabase_url'
    ) || '/functions/v1/send-abandoned-checkout-reminder',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || (
        SELECT decrypted_secret
        FROM vault.decrypted_secrets
        WHERE name = 'service_role_key'
      )
    ),
    body := '{}'::jsonb
  );
  $$
);
