-- Booking mileage logs: one-way business↔ customer miles + round-trip for delivery trips

CREATE TABLE IF NOT EXISTS public.booking_mileage_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id bigint NOT NULL REFERENCES public.bookings(id) ON DELETE CASCADE,
  customer_id bigint REFERENCES public.customers(id) ON DELETE SET NULL,
  service_id bigint,
  service_name text,
  service_type text,
  one_way_miles numeric(10, 2) NOT NULL DEFAULT 0,
  round_trip_miles numeric(10, 2) NOT NULL DEFAULT 0,
  trip_kind text NOT NULL DEFAULT 'none'
    CHECK (trip_kind IN ('delivery_pickup', 'one_way', 'none')),
  address_snapshot jsonb,
  source text NOT NULL DEFAULT 'booking_create'
    CHECK (source IN ('booking_create', 'reschedule_address', 'backfill')),
  recorded_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT booking_mileage_logs_booking_id_unique UNIQUE (booking_id)
);

CREATE INDEX IF NOT EXISTS idx_booking_mileage_logs_recorded_at
  ON public.booking_mileage_logs (recorded_at DESC);

CREATE INDEX IF NOT EXISTS idx_booking_mileage_logs_service
  ON public.booking_mileage_logs (service_name);

CREATE INDEX IF NOT EXISTS idx_booking_mileage_logs_customer
  ON public.booking_mileage_logs (customer_id);

COMMENT ON TABLE public.booking_mileage_logs IS
  'One-way Google miles per booking for route/maintenance tracking; round_trip = one_way * 2 for delivery trips';

ALTER TABLE public.booking_mileage_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS booking_mileage_logs_admin_all ON public.booking_mileage_logs;
CREATE POLICY booking_mileage_logs_admin_all
  ON public.booking_mileage_logs
  FOR ALL
  USING (public.is_admin() OR auth.role() = 'service_role')
  WITH CHECK (public.is_admin() OR auth.role() = 'service_role');

DROP POLICY IF EXISTS booking_mileage_logs_select_own ON public.booking_mileage_logs;
CREATE POLICY booking_mileage_logs_select_own
  ON public.booking_mileage_logs
  FOR SELECT
  USING (
    customer_id = public.current_customer_id()
    OR public.is_admin()
    OR auth.role() = 'service_role'
  );

-- Resolve whether booking has a delivery/pickup trip that should log round-trip miles
CREATE OR REPLACE FUNCTION public.booking_has_delivery_trip(p_booking public.bookings)
RETURNS boolean
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
  v_addons jsonb := COALESCE(p_booking.addons, '{}'::jsonb);
  v_plan jsonb := COALESCE(p_booking.plan, '{}'::jsonb);
  v_plan_id bigint;
  v_name text;
BEGIN
  IF COALESCE((v_addons->>'isDelivery')::boolean, false)
     OR COALESCE((v_addons->>'deliveryService')::boolean, false) THEN
    RETURN true;
  END IF;

  IF p_booking.delivery_address IS NOT NULL
     AND NULLIF(trim(COALESCE(p_booking.delivery_address->>'street', '')), '') IS NOT NULL THEN
    -- Self-pickup dump loader (plan id 2) without delivery flag is customer pickup
    v_plan_id := NULLIF(v_plan->>'id', '')::bigint;
    IF v_plan_id = 2
       AND NOT COALESCE((v_addons->>'isDelivery')::boolean, false) THEN
      RETURN false;
    END IF;
    RETURN true;
  END IF;

  v_plan_id := NULLIF(v_plan->>'id', '')::bigint;
  v_name := lower(COALESCE(v_plan->>'name', ''));
  IF v_plan_id IN (1, 4) THEN
    RETURN true;
  END IF;
  IF v_name LIKE '%delivery%' THEN
    RETURN true;
  END IF;

  RETURN false;
END;
$$;

CREATE OR REPLACE FUNCTION public.upsert_booking_mileage_log(
  p_booking_id bigint,
  p_one_way_miles numeric DEFAULT NULL,
  p_source text DEFAULT 'booking_create',
  p_address_snapshot jsonb DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO public
AS $$
DECLARE
  v_booking public.bookings%ROWTYPE;
  v_customer_miles numeric;
  v_one_way numeric;
  v_trip boolean;
  v_trip_kind text;
  v_round numeric;
  v_service_id bigint;
  v_service_name text;
  v_service_type text;
  v_addr jsonb;
  v_id bigint;
  v_source text;
BEGIN
  IF p_booking_id IS NULL THEN
    RETURN NULL;
  END IF;

  SELECT * INTO v_booking FROM public.bookings WHERE id = p_booking_id;
  IF NOT FOUND THEN
    RETURN NULL;
  END IF;

  v_source := COALESCE(NULLIF(trim(p_source), ''), 'booking_create');
  IF v_source NOT IN ('booking_create', 'reschedule_address', 'backfill') THEN
    v_source := 'booking_create';
  END IF;

  SELECT c.distance_miles INTO v_customer_miles
  FROM public.customers c
  WHERE c.id = v_booking.customer_id;

  v_one_way := COALESCE(
    NULLIF(p_one_way_miles, 0),
    NULLIF(v_booking.distance_miles, 0),
    NULLIF(v_customer_miles, 0),
    0
  );

  -- Persist one-way on booking when we have a value
  IF v_one_way > 0 AND (v_booking.distance_miles IS NULL OR v_booking.distance_miles = 0 OR p_one_way_miles IS NOT NULL) THEN
    UPDATE public.bookings
    SET distance_miles = v_one_way
    WHERE id = p_booking_id;
  END IF;

  v_trip := public.booking_has_delivery_trip(v_booking);
  IF NOT v_trip THEN
    -- Still show/store one-way on booking, but no Financial Books trip log
    RETURN NULL;
  END IF;

  IF v_one_way <= 0 THEN
    RETURN NULL;
  END IF;

  v_trip_kind := 'delivery_pickup';
  v_round := round(v_one_way * 2, 2);
  v_service_id := NULLIF(v_booking.plan->>'id', '')::bigint;
  v_service_name := COALESCE(v_booking.plan->>'name', 'Unknown Service');
  v_service_type := COALESCE(v_booking.plan->>'service_type', v_booking.delivery_type, 'delivery');
  v_addr := COALESCE(
    p_address_snapshot,
    v_booking.delivery_address,
    jsonb_build_object(
      'street', v_booking.street,
      'city', v_booking.city,
      'state', v_booking.state,
      'zip', v_booking.zip
    )
  );

  INSERT INTO public.booking_mileage_logs (
    booking_id,
    customer_id,
    service_id,
    service_name,
    service_type,
    one_way_miles,
    round_trip_miles,
    trip_kind,
    address_snapshot,
    source,
    recorded_at,
    updated_at
  )
  VALUES (
    p_booking_id,
    v_booking.customer_id,
    v_service_id,
    v_service_name,
    v_service_type,
    round(v_one_way, 2),
    v_round,
    v_trip_kind,
    v_addr,
    v_source,
    now(),
    now()
  )
  ON CONFLICT (booking_id) DO UPDATE SET
    customer_id = EXCLUDED.customer_id,
    service_id = EXCLUDED.service_id,
    service_name = EXCLUDED.service_name,
    service_type = EXCLUDED.service_type,
    one_way_miles = EXCLUDED.one_way_miles,
    round_trip_miles = EXCLUDED.round_trip_miles,
    trip_kind = EXCLUDED.trip_kind,
    address_snapshot = EXCLUDED.address_snapshot,
    source = EXCLUDED.source,
    updated_at = now()
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;

GRANT EXECUTE ON FUNCTION public.upsert_booking_mileage_log(bigint, numeric, text, jsonb)
  TO anon, authenticated, service_role;

-- Extend create_pending_booking to persist distance_miles + mileage log
CREATE OR REPLACE FUNCTION public.create_pending_booking(payload jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO public
AS $$
DECLARE
  new_id bigint;
  new_customer_id bigint;
  v_distance numeric;
BEGIN
  v_distance := COALESCE(NULLIF(payload->>'distance_miles', '')::numeric, 0);

  INSERT INTO bookings (
    name,
    first_name,
    last_name,
    email,
    phone,
    street,
    city,
    state,
    zip,
    contact_address,
    delivery_address,
    drop_off_date,
    pickup_date,
    drop_off_time_slot,
    pickup_time_slot,
    plan,
    addons,
    total_price,
    subtotal_before_tax,
    tax_amount,
    tax_rate_used,
    delivery_type,
    status,
    notes,
    was_verification_skipped,
    verification_notes,
    distance_miles
  )
  VALUES (
    payload->>'name',
    payload->>'first_name',
    payload->>'last_name',
    payload->>'email',
    payload->>'phone',
    payload->>'street',
    payload->>'city',
    payload->>'state',
    payload->>'zip',
    payload->'contact_address',
    payload->'delivery_address',
    (payload->>'drop_off_date')::date,
    (payload->>'pickup_date')::date,
    payload->>'drop_off_time_slot',
    payload->>'pickup_time_slot',
    payload->'plan',
    payload->'addons',
    (payload->>'total_price')::real,
    COALESCE((payload->>'subtotal_before_tax')::numeric, 0),
    COALESCE((payload->>'tax_amount')::numeric, 0),
    COALESCE((payload->>'tax_rate_used')::numeric, 0),
    payload->>'delivery_type',
    'pending_payment',
    payload->>'notes',
    COALESCE((payload->>'was_verification_skipped')::boolean, false),
    payload->>'verification_notes',
    v_distance
  )
  RETURNING id, customer_id INTO new_id, new_customer_id;

  IF jsonb_typeof(payload->'addons'->'agreementFeeSnapshot') = 'array' THEN
    INSERT INTO public.booking_fee_snapshots (
      booking_id,
      fee_key,
      fee_name,
      fee_description,
      fee_value,
      is_percentage,
      snapshot_source,
      captured_at
    )
    SELECT
      new_id,
      COALESCE(item->>'fee_key', 'unknown_fee_key'),
      COALESCE(item->>'fee_name', item->>'fee_key', 'Unknown Fee'),
      item->>'fee_description',
      COALESCE(NULLIF(item->>'fee_value', '')::numeric, 0),
      COALESCE((item->>'is_percentage')::boolean, false),
      COALESCE(item->>'source', 'agreement_step6_acceptance'),
      COALESCE((item->>'captured_at')::timestamptz, NOW())
    FROM jsonb_array_elements(payload->'addons'->'agreementFeeSnapshot') AS item;
  END IF;

  PERFORM public.sync_booking_protection_plans(new_id);

  -- Prefer payload miles; otherwise customer profile one-way miles
  IF v_distance <= 0 AND new_customer_id IS NOT NULL THEN
    SELECT COALESCE(distance_miles, 0) INTO v_distance
    FROM public.customers
    WHERE id = new_customer_id;
  END IF;

  PERFORM public.upsert_booking_mileage_log(
    new_id,
    NULLIF(v_distance, 0),
    'booking_create',
    COALESCE(payload->'delivery_address', payload->'contact_address')
  );

  RETURN jsonb_build_object(
    'id', new_id,
    'customer_id', new_customer_id
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.create_pending_booking(jsonb) TO anon, authenticated, service_role;

-- Backfill existing delivery bookings from known one-way miles
INSERT INTO public.booking_mileage_logs (
  booking_id,
  customer_id,
  service_id,
  service_name,
  service_type,
  one_way_miles,
  round_trip_miles,
  trip_kind,
  address_snapshot,
  source,
  recorded_at,
  updated_at
)
SELECT
  b.id,
  b.customer_id,
  NULLIF(b.plan->>'id', '')::bigint,
  COALESCE(b.plan->>'name', 'Unknown Service'),
  COALESCE(b.plan->>'service_type', b.delivery_type, 'delivery'),
  round(miles.one_way, 2),
  round(miles.one_way * 2, 2),
  'delivery_pickup',
  COALESCE(
    b.delivery_address,
    jsonb_build_object('street', b.street, 'city', b.city, 'state', b.state, 'zip', b.zip)
  ),
  'backfill',
  COALESCE(b.created_at, now()),
  now()
FROM public.bookings b
LEFT JOIN public.customers c ON c.id = b.customer_id
CROSS JOIN LATERAL (
  SELECT COALESCE(
    NULLIF(b.distance_miles, 0),
    NULLIF(c.distance_miles, 0),
    0
  ) AS one_way
) miles
WHERE miles.one_way > 0
  AND public.booking_has_delivery_trip(b)
ON CONFLICT (booking_id) DO NOTHING;
